In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
# Loading dataset
insurance_data = pd.read_csv("insuranceData.csv")

In [3]:
# display first 5 rows of the dataset
insurance_data.head()
insurance_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   bmi       1338 non-null   float64
 2   children  1338 non-null   int64
 3   smoker    1338 non-null   str
 4   charges   1338 non-null   float64
dtypes: float64(2), int64(2), str(1)
memory usage: 52.4 KB

In [4]:
# Make a copy of the original dataset to apply LabelEncoder safely
label_encoded_data = insurance_data.copy()

# Create a LabelEncoder object
label_encoder = LabelEncoder()

# Apply LabelEncoder to the smoker column
# This converts "yes" and "no" into numeric values like 1 and 0

label_encoded_data["smoker"] = label_encoder.fit_transform(label_encoded_data["smoker"])

# Display the first 5 rows after label encoding
label_encoded_data.head()

   age     bmi  children  smoker      charges
0   19  27.900         0       1  16884.92400
1   18  33.770         1       0   1725.55230
2   28  33.000         3       0   4449.46200
3   33  22.705         0       0  21984.47061
4   32  28.880         0       0   3866.85520

In [5]:
# Make another copy of the original dataset for OneHotEncoding

onehot_data = insurance_data.copy()

# Apply OneHotEncoder to the smoker column using pandas get_dummies
# This will create separate columns for smoker_no and smoker_yes

onehot_data = pd.get_dummies(onehot_data, columns=["smoker"], drop_first=True)

# Display the first 5 rows after one hot encoding
onehot_data.head()

   age     bmi  children      charges  smoker_yes
0   19  27.900         0  16884.92400        True
1   18  33.770         1   1725.55230       False
2   28  33.000         3   4449.46200       False
3   33  22.705         0  21984.47061       False
4   32  28.880         0   3866.85520       False

In [6]:
# Set the independent variables or features
# These are the columns used to predict the insurance charges

X = onehot_data.drop("charges", axis=1)

# Set the dependent variable or target
# This is the column we want to predict

y = onehot_data["charges"]

In [7]:
# Split the data into training and testing sets
# 85% of the data will be used for training
# 15% of the data will be used for testing

X_train, X_test, y_train, y_test = train_test_split(
    X, 
    y, 
    test_size=0.15, 
    random_state=42
)

In [8]:
# Create a Linear Regression model

model = LinearRegression()

# Train the model using the training data

model.fit(X_train, y_train)
# Use the trained model to predict insurance charges using the test data

y_pred = model.predict(X_test)

In [9]:
# Use the trained model to predict insurance charges using the test data

# Check how well the model performed

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)
print("R2 Score:", r2)

# Create a table to compare the actual charges and predicted charges

comparison = pd.DataFrame({
    "Actual Charges": y_test,
    "Predicted Charges": y_pred
})

comparison.head()

Mean Absolute Error: 4084.844045825546
Mean Squared Error: 31416287.36289385
Root Mean Squared Error: 5605.023404312764
R2 Score: 0.7936773121565155

      Actual Charges  Predicted Charges
764       9095.06825        8615.731479
887       5272.17580        6958.236584
890      29330.98315       37016.448856
1293      9301.89355        9481.032760
259      33750.29180       26894.375908